language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install coveralls

script:
   coverage run --source=dcm_spec_tools/spec_reader,dcm_spec_tools/validator ./run_tests.py

after_success:
  - coveralls
