language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8-dev"

install:
  - pip install -r requirements-dev.txt
  - pip install codecov

script:
   coverage run --branch --source=dcm_spec_tools/spec_reader,dcm_spec_tools/validator --omit=*/tests/*.py ./run_tests.py

after_success:
  - codecov
